name: golang-pipeline

# Определение событий, на которые реагирует workflow
on:
  push:
    branches:
      - first-iteration    # Запускает workflow при пуше в ветку first-iteration
    tags:
      - 'v*.*.*'  # Запускает workflow при добавлении тегов, например, v1.0.0

jobs:
  # Job для тестирования кода
  test:
    name: Lint and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Install dependencies
        run: go mod download

      - name: Run Linter
        run: go vet ./...

      - name: Run Tests
        run: go test -v ./...

  # Job для сборки и публикации Docker-образа
  deploy:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: test  # Выполняется после успешного завершения тестов
    if: startsWith(github.ref, 'refs/tags/')  # Запускается только при наличии тега

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.ref_name }}

      - name: Image digest
        run: echo ${{ steps.build.outputs.digest }}
